### PR TITLE
Gather WebDriver logs if test is marked public

### PR DESCRIPTION
**Pull request by davehunt**
Sorry, @bobsilverberg, another patch to review!

### CODE REVIEW

**Comment by bobsilverberg** [comment]
I find this a bit confusing. We only include the logs is a test is marked public, but this is because the logs can include sensitive information. Shouldn't we then *not* include the logs for tests marked public, as one would assume those test results will be visible by everyone?

**Comment by davehunt** [comment]
@bobsilverberg we're marking a test's privacy as public, therefore explicitly stating that any information about it (including the logs) is allowed. This is no different from how we used to handle RC logs. FWIW I'm thinking of changing this to a config option such as `selenium_collect_logs_on_failure` with a default of false. I don't like that this feature will otherwise be barely ever seen.

**Comment by davehunt** [comment]
I also don't like intermingling with the Sauce Labs privacy tag. I really worked on this pull because I was waiting for another to land. I'm fine with it remaining open while we work out the best way to move forward (may involve more refactorings first).

**Comment by davehunt** [comment]
I'm going to close this. It will be implemented in pytest-selenium: https://github.com/davehunt/pytest-selenium/

**Pull request closed without merging**
